"""Add chief_complaint to appointments

Revision ID: c639c6900bc9
Revises: f008910a9304
Create Date: 2026-01-17 08:07:53.554563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c639c6900bc9'
down_revision: Union[str, None] = 'f008910a9304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('chief_complaint', sa.String(), nullable=True))
    op.drop_constraint('clinics_clinic_code_key', 'clinics', type_='unique')
    op.create_index(op.f('ix_clinics_clinic_code'), 'clinics', ['clinic_code'], unique=True)
    op.drop_constraint('doctors_doctor_code_key', 'doctors', type_='unique')
    op.create_index(op.f('ix_doctors_doctor_code'), 'doctors', ['doctor_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_doctor_code'), table_name='doctors')
    op.create_unique_constraint('doctors_doctor_code_key', 'doctors', ['doctor_code'])
    op.drop_index(op.f('ix_clinics_clinic_code'), table_name='clinics')
    op.create_unique_constraint('clinics_clinic_code_key', 'clinics', ['clinic_code'])
    op.drop_column('appointments', 'chief_complaint')
    # ### end Alembic commands ###
